name: pipeline1

on:
  workflow_dispatch: 

jobs:
  my_job:
    name: MY JOB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0 
      - name: hi
        run: echo "Hello World"

      - name: list files
        run: ls -a
